# Remove user from group
DELETE http://46.101.181.115:8000/api/groups/1/users/17

###
# Add user to group
PUT http://46.101.181.115:8000/api/groups/1/users/17

###
# Remove room from group
DELETE localhost:8080/api/groups/1/rooms/36

###
# Add room to group
PUT localhost:8080/api/groups/2/rooms/2