# Create reservation
POST http://46.101.181.115:8000/api/reservations/
Content-Type: application/json

{
  "date": {
    "year": "2020",
    "month": "10",
    "day": "10"
  },
  "time_from": {
    "hour": "10",
    "minute": "0"
  },
  "time_to": {
    "hour": "12",
    "minute": "0"
  },
  "user": 1,
  "room": 1
}

###
# Update reservation
PUT http://46.101.181.115:8000/api/reservations/14
Content-Type: application/json

{
  "date": {
    "year": "2020",
    "month": "10",
    "day": "10"
  },
  "time_from": {
    "hour": "15",
    "minute": "0"
  },
  "time_to": {
    "hour": "16",
    "minute": "0"
  },
  "user": 1,
  "room": 1
}

###
# Remove reservation
DELETE http://46.101.181.115:8000/api/reservations/15

###
# Get one reservation
GET http://46.101.181.115:8000/api/reservations/1

###
# Approve reservation
PUT http://46.101.181.115:8000/api/reservations/15/approve

###
# Reject reservation
PUT http://46.101.181.115:8000/api/reservations/13/reject

###
# Add attendee
PUT http://46.101.181.115:8000/api/reservations/13/attendees/2

###
# Remove attendee
DELETE http://46.101.181.115:8000/api/reservations/13/attendees/1
